import type { Block } from 'payload'

export const CoursesHeroBlock: Block = {
  slug: 'coursesHero',
  labels: { singular: 'Courses Hero', plural: 'Courses Heroes' },
  fields: [
    { name: 'eyebrow', type: 'text', defaultValue: 'All Courses' },
    { name: 'headingMain', type: 'text', defaultValue: 'Learn at your', required: true },
    { name: 'headingAccent', type: 'text', defaultValue: 'own pace.' },
    {
      name: 'subtext',
      type: 'textarea',
      defaultValue:
        'Explore our full catalogue of structured language programmes — from beginner to advanced, group to private, online to in-person.',
    },
    {
      name: 'stats',
      type: 'array',
      maxRows: 4,
      fields: [
        { name: 'value', type: 'text', required: true },
        { name: 'label', type: 'text', required: true },
      ],
      defaultValue: [
        { value: '40+', label: 'Courses' },
        { value: '20+', label: 'Languages' },
        { value: 'A1–C2', label: 'All Levels' },
        { value: '100%', label: 'Live Classes' },
      ],
    },
  ],
}

export const CoursesListBlock: Block = {
  slug: 'coursesList',
  labels: { singular: 'Courses List', plural: 'Courses Lists' },
  fields: [
    { name: 'eyebrow', type: 'text', defaultValue: 'Browse' },
    { name: 'heading', type: 'text', defaultValue: 'All programmes' },
    {
      name: 'courses',
      type: 'array',
      label: 'Courses',
      minRows: 1,
      fields: [
        { name: 'flag', type: 'text', label: 'Flag emoji', defaultValue: '🇬🇧' },
        { name: 'language', type: 'text', label: 'Language', required: true },
        { name: 'title', type: 'text', label: 'Course Title', required: true },
        {
          name: 'format',
          type: 'select',
          label: 'Format',
          options: [
            { label: 'Group', value: 'group' },
            { label: 'Private', value: 'private' },
            { label: 'Intensive', value: 'intensive' },
            { label: 'Online', value: 'online' },
            { label: 'Business', value: 'business' },
          ],
          defaultValue: 'group',
        },
        { name: 'level', type: 'text', label: 'Level (e.g. A1–A2)', defaultValue: 'A1–A2' },
        { name: 'duration', type: 'text', label: 'Duration (e.g. 3 months)' },
        { name: 'sessions', type: 'text', label: 'Sessions/week (e.g. 3×90 min)' },
        { name: 'classSize', type: 'text', label: 'Class size (e.g. Max 8)' },
        { name: 'price', type: 'text', label: 'Price (e.g. ₹4,999)', required: true },
        { name: 'pricePeriod', type: 'text', label: 'Price period', defaultValue: '/month' },
        { name: 'featured', type: 'checkbox', label: 'Featured', defaultValue: false },
        { name: 'url', type: 'text', label: 'Enroll URL', defaultValue: '/enroll' },
        {
          name: 'tags',
          type: 'array',
          fields: [{ name: 'tag', type: 'text' }],
        },
        {
          name: 'highlights',
          type: 'array',
          label: 'Highlights (bullet points)',
          fields: [{ name: 'text', type: 'text' }],
        },
      ],
      defaultValue: [
        {
          flag: '🇬🇧',
          language: 'English',
          title: 'Beginner English',
          format: 'group',
          level: 'A1–A2',
          duration: '3 months',
          sessions: '3 × 90 min',
          classSize: 'Max 8',
          price: '₹4,999',
          pricePeriod: '/month',
          featured: false,
          url: '/enroll',
          tags: [{ tag: 'IELTS Prep' }, { tag: 'Live Classes' }],
          highlights: [
            { text: 'Native speaker instructor' },
            { text: 'Weekly progress reports' },
            { text: 'Study materials included' },
          ],
        },
        {
          flag: '🇬🇧',
          language: 'English',
          title: 'Business English',
          format: 'business',
          level: 'B1–C1',
          duration: '4 months',
          sessions: '2 × 2 hours',
          classSize: 'Max 6',
          price: '₹8,999',
          pricePeriod: '/month',
          featured: true,
          url: '/enroll',
          tags: [{ tag: 'Business' }, { tag: 'Presentations' }],
          highlights: [
            { text: 'Real business scenarios' },
            { text: 'Email & report writing' },
            { text: 'Interview preparation' },
          ],
        },
        {
          flag: '🇪🇸',
          language: 'Spanish',
          title: 'Spanish for Beginners',
          format: 'group',
          level: 'A1–A2',
          duration: '3 months',
          sessions: '3 × 90 min',
          classSize: 'Max 8',
          price: '₹4,999',
          pricePeriod: '/month',
          featured: false,
          url: '/enroll',
          tags: [{ tag: 'DELE' }, { tag: 'Live Classes' }],
          highlights: [
            { text: 'Cultural immersion' },
            { text: 'Conversational focus' },
            { text: 'DELE exam prep' },
          ],
        },
        {
          flag: '🇫🇷',
          language: 'French',
          title: 'French Intensive',
          format: 'intensive',
          level: 'A2–B1',
          duration: '6 weeks',
          sessions: '5 × 2 hours',
          classSize: 'Max 6',
          price: '₹12,999',
          pricePeriod: '/month',
          featured: true,
          url: '/enroll',
          tags: [{ tag: 'DELF' }, { tag: 'Fast-track' }],
          highlights: [
            { text: 'Daily live classes' },
            { text: 'DELF preparation' },
            { text: 'Conversation partner' },
          ],
        },
        {
          flag: '🇯🇵',
          language: 'Japanese',
          title: 'Japanese N5–N3',
          format: 'private',
          level: 'N5–N3',
          duration: '5 months',
          sessions: '2 × 90 min',
          classSize: '1-on-1',
          price: '₹9,999',
          pricePeriod: '/month',
          featured: false,
          url: '/enroll',
          tags: [{ tag: 'JLPT' }, { tag: 'Private' }],
          highlights: [
            { text: 'Personalised pacing' },
            { text: 'Hiragana to Kanji' },
            { text: 'JLPT exam strategy' },
          ],
        },
        {
          flag: '🇩🇪',
          language: 'German',
          title: 'German A1–B1',
          format: 'online',
          level: 'A1–B1',
          duration: '4 months',
          sessions: '3 × 90 min',
          classSize: 'Max 10',
          price: '₹5,999',
          pricePeriod: '/month',
          featured: false,
          url: '/enroll',
          tags: [{ tag: 'Goethe' }, { tag: 'Online' }],
          highlights: [
            { text: 'Live online classes' },
            { text: 'Goethe-Zertifikat prep' },
            { text: 'Flexible timings' },
          ],
        },
      ],
    },
  ],
}

export const CoursesCompareBlock: Block = {
  slug: 'coursesCompare',
  labels: { singular: 'Compare Formats', plural: 'Compare Formats' },
  fields: [
    { name: 'eyebrow', type: 'text', defaultValue: 'Formats' },
    { name: 'heading', type: 'text', defaultValue: 'Which format suits you?' },
    {
      name: 'formats',
      type: 'array',
      fields: [
        { name: 'icon', type: 'text', defaultValue: '👥' },
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea' },
        { name: 'bestFor', type: 'text', label: 'Best for' },
        { name: 'price', type: 'text', label: 'Starting price' },
        { name: 'featured', type: 'checkbox', defaultValue: false },
        { name: 'url', type: 'text', defaultValue: '/courses' },
      ],
      defaultValue: [
        {
          icon: '👥',
          title: 'Group Classes',
          description:
            'Learn with peers in a structured, energetic environment. Best value for money.',
          bestFor: 'Budget-conscious learners',
          price: 'From ₹4,999/mo',
          featured: false,
          url: '/courses',
        },
        {
          icon: '🎯',
          title: 'Private Tutoring',
          description: 'One-on-one sessions fully tailored to your goals, pace, and schedule.',
          bestFor: 'Fast-tracked learners',
          price: 'From ₹9,999/mo',
          featured: true,
          url: '/courses',
        },
        {
          icon: '⚡',
          title: 'Intensive',
          description: 'Daily classes for rapid progress. Perfect for exam prep or relocation.',
          bestFor: 'Deadline-driven learners',
          price: 'From ₹12,999/mo',
          featured: false,
          url: '/courses',
        },
        {
          icon: '💼',
          title: 'Business',
          description: 'Workplace language skills — emails, presentations, negotiations.',
          bestFor: 'Professionals & teams',
          price: 'From ₹8,999/mo',
          featured: false,
          url: '/courses',
        },
      ],
    },
  ],
}

export const CoursesCtaBlock: Block = {
  slug: 'coursesCta',
  labels: { singular: 'Courses CTA', plural: 'Courses CTAs' },
  fields: [
    { name: 'heading', type: 'text', defaultValue: 'Not sure where to start?' },
    {
      name: 'subtext',
      type: 'text',
      defaultValue:
        'Book a free 15-minute consultation and we will match you with the perfect programme.',
    },
    { name: 'primaryLabel', type: 'text', defaultValue: 'Book Free Consultation' },
    { name: 'primaryUrl', type: 'text', defaultValue: '/contact' },
    { name: 'secondaryLabel', type: 'text', defaultValue: 'Take Assessment' },
    { name: 'secondaryUrl', type: 'text', defaultValue: '/assessment' },
  ],
}
