import type { Block } from 'payload'

export const LanguagesHeroBlock: Block = {
  slug: 'languagesHero',
  labels: { singular: 'Languages Hero', plural: 'Languages Heroes' },
  fields: [
    { name: 'eyebrow', type: 'text', defaultValue: 'All Languages' },
    { name: 'headingMain', type: 'text', defaultValue: 'Find your', required: true },
    { name: 'headingAccent', type: 'text', defaultValue: 'perfect language.' },
    {
      name: 'subtext',
      type: 'textarea',
      defaultValue:
        'From conversational basics to professional fluency — explore 20+ languages taught by native speakers with CEFR-aligned programmes.',
    },
    {
      name: 'searchPlaceholder',
      type: 'text',
      defaultValue: 'Search a language...',
    },
    {
      name: 'stats',
      type: 'array',
      maxRows: 3,
      fields: [
        { name: 'value', type: 'text', required: true },
        { name: 'label', type: 'text', required: true },
      ],
      defaultValue: [
        { value: '20+', label: 'Languages' },
        { value: '5,000+', label: 'Students' },
        { value: 'A1–C2', label: 'All Levels' },
      ],
    },
  ],
}

export const LanguagesGridBlock: Block = {
  slug: 'languagesGrid',
  labels: { singular: 'Languages Grid', plural: 'Languages Grids' },
  fields: [
    { name: 'eyebrow', type: 'text', defaultValue: 'Explore' },
    { name: 'heading', type: 'text', defaultValue: 'All languages we offer' },
    {
      name: 'filterLabel',
      type: 'text',
      defaultValue: 'Filter by region',
    },
    {
      name: 'languages',
      type: 'array',
      label: 'Languages',
      minRows: 1,
      fields: [
        { name: 'flag', type: 'text', label: 'Flag emoji', defaultValue: '🇬🇧' },
        { name: 'code', type: 'text', label: 'Country code (e.g. GB)', required: true },
        { name: 'name', type: 'text', label: 'Language name', required: true },
        { name: 'nativeName', type: 'text', label: 'Native name (e.g. English)' },
        { name: 'region', type: 'text', label: 'Region (e.g. European)' },
        { name: 'level', type: 'text', label: 'Levels (e.g. A1–C2)' },
        { name: 'students', type: 'text', label: 'Students count (e.g. 1,200+)' },
        { name: 'instructors', type: 'number', label: 'Number of instructors' },
        {
          name: 'tags',
          type: 'array',
          fields: [{ name: 'tag', type: 'text' }],
          label: 'Tags (e.g. Business, IELTS)',
        },
        { name: 'featured', type: 'checkbox', label: 'Featured', defaultValue: false },
        { name: 'url', type: 'text', label: 'Language page URL' },
        {
          name: 'color',
          type: 'select',
          label: 'Accent color',
          options: [
            { label: 'Sage', value: 'sage' },
            { label: 'Brown', value: 'brown' },
            { label: 'Yellow', value: 'yellow' },
            { label: 'Black', value: 'black' },
          ],
          defaultValue: 'sage',
        },
      ],
      defaultValue: [
        {
          flag: '🇬🇧',
          code: 'EN',
          name: 'English',
          nativeName: 'English',
          region: 'European',
          level: 'A1–C2',
          students: '1,200+',
          instructors: 12,
          tags: [{ tag: 'Business' }, { tag: 'IELTS' }, { tag: 'Academic' }],
          featured: true,
          url: '/languages/english',
          color: 'sage',
        },
        {
          flag: '🇪🇸',
          code: 'ES',
          name: 'Spanish',
          nativeName: 'Español',
          region: 'European',
          level: 'A1–C2',
          students: '980+',
          instructors: 10,
          tags: [{ tag: 'DELE' }, { tag: 'Latin' }, { tag: 'Iberian' }],
          featured: true,
          url: '/languages/spanish',
          color: 'brown',
        },
        {
          flag: '🇫🇷',
          code: 'FR',
          name: 'French',
          nativeName: 'Français',
          region: 'European',
          level: 'A1–C2',
          students: '850+',
          instructors: 9,
          tags: [{ tag: 'DELF' }, { tag: 'DALF' }, { tag: 'Parisian' }],
          featured: true,
          url: '/languages/french',
          color: 'yellow',
        },
        {
          flag: '🇩🇪',
          code: 'DE',
          name: 'German',
          nativeName: 'Deutsch',
          region: 'European',
          level: 'A1–C2',
          students: '620+',
          instructors: 7,
          tags: [{ tag: 'Goethe' }, { tag: 'Business' }],
          featured: false,
          url: '/languages/german',
          color: 'sage',
        },
        {
          flag: '🇯🇵',
          code: 'JP',
          name: 'Japanese',
          nativeName: '日本語',
          region: 'Asian',
          level: 'N5–N1',
          students: '740+',
          instructors: 8,
          tags: [{ tag: 'JLPT' }, { tag: 'Manga' }, { tag: 'Business' }],
          featured: true,
          url: '/languages/japanese',
          color: 'black',
        },
        {
          flag: '🇨🇳',
          code: 'ZH',
          name: 'Mandarin',
          nativeName: '普通话',
          region: 'Asian',
          level: 'HSK 1–6',
          students: '560+',
          instructors: 6,
          tags: [{ tag: 'HSK' }, { tag: 'Business' }],
          featured: false,
          url: '/languages/mandarin',
          color: 'brown',
        },
        {
          flag: '🇰🇷',
          code: 'KO',
          name: 'Korean',
          nativeName: '한국어',
          region: 'Asian',
          level: 'TOPIK 1–6',
          students: '430+',
          instructors: 5,
          tags: [{ tag: 'TOPIK' }, { tag: 'K-Culture' }],
          featured: false,
          url: '/languages/korean',
          color: 'sage',
        },
        {
          flag: '🇦🇪',
          code: 'AR',
          name: 'Arabic',
          nativeName: 'العربية',
          region: 'Middle Eastern',
          level: 'A1–C1',
          students: '380+',
          instructors: 4,
          tags: [{ tag: 'MSA' }, { tag: 'Business' }],
          featured: false,
          url: '/languages/arabic',
          color: 'yellow',
        },
        {
          flag: '🇮🇹',
          code: 'IT',
          name: 'Italian',
          nativeName: 'Italiano',
          region: 'European',
          level: 'A1–C2',
          students: '310+',
          instructors: 4,
          tags: [{ tag: 'CILS' }, { tag: 'Culture' }],
          featured: false,
          url: '/languages/italian',
          color: 'brown',
        },
        {
          flag: '🇵🇹',
          code: 'PT',
          name: 'Portuguese',
          nativeName: 'Português',
          region: 'European',
          level: 'A1–C1',
          students: '270+',
          instructors: 3,
          tags: [{ tag: 'Brazil' }, { tag: 'Europe' }],
          featured: false,
          url: '/languages/portuguese',
          color: 'sage',
        },
      ],
    },
  ],
}

export const LanguageWhyBlock: Block = {
  slug: 'languageWhy',
  labels: { singular: 'Why Learn With Us', plural: 'Why Learn With Us' },
  fields: [
    { name: 'eyebrow', type: 'text', defaultValue: 'Our Approach' },
    { name: 'heading', type: 'text', defaultValue: 'Why learn with LinguaMosaic?' },
    {
      name: 'features',
      type: 'array',
      label: 'Features',
      fields: [
        { name: 'icon', type: 'text', defaultValue: '🌱' },
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea' },
      ],
      defaultValue: [
        {
          icon: '🧑‍🏫',
          title: 'Native-Speaker Instructors',
          description:
            'Every class is taught by certified native speakers who bring authentic accents and cultural nuance to every lesson.',
        },
        {
          icon: '📋',
          title: 'CEFR-Aligned Curriculum',
          description:
            'Our programmes map directly to international CEFR standards — so your progress is measurable and globally recognised.',
        },
        {
          icon: '🎯',
          title: 'Personalised Learning Path',
          description:
            'We assess your level first, then craft a path built around your goals, schedule, and learning style.',
        },
        {
          icon: '🌍',
          title: 'Cultural Immersion',
          description:
            'Language is culture. Every programme weaves in cultural context, idioms, and real-world scenarios.',
        },
        {
          icon: '📱',
          title: 'Flexible Online & Offline',
          description:
            'Attend in-person at our Noida centre or join live online classes from anywhere in India.',
        },
        {
          icon: '🏆',
          title: 'Exam Preparation',
          description:
            'Dedicated exam prep tracks for IELTS, DELF, DELE, JLPT, HSK, Goethe-Zertifikat, and more.',
        },
      ],
    },
  ],
}

export const LanguageCtaBlock: Block = {
  slug: 'languageCta',
  labels: { singular: 'Language CTA', plural: 'Language CTAs' },
  fields: [
    { name: 'heading', type: 'text', defaultValue: 'Not sure which language to start?' },
    {
      name: 'subtext',
      type: 'text',
      defaultValue: 'Take our free 3-minute assessment and get a personalised recommendation.',
    },
    { name: 'primaryLabel', type: 'text', defaultValue: 'Take Assessment' },
    { name: 'primaryUrl', type: 'text', defaultValue: '/assessment' },
    { name: 'secondaryLabel', type: 'text', defaultValue: 'Talk to an Advisor' },
    { name: 'secondaryUrl', type: 'text', defaultValue: '/contact' },
  ],
}
