import type { Block } from 'payload'

export const PricingBlock: Block = {
  slug: 'pricing',
  labels: {
    singular: 'Pricing Block',
    plural: 'Pricing Blocks',
  },
  fields: [
    {
      name: 'eyebrow',
      type: 'text',
      label: 'Eyebrow Label',
      defaultValue: 'Pricing',
    },
    {
      name: 'heading',
      type: 'text',
      label: 'Heading',
      defaultValue: 'Simple, transparent pricing',
      required: true,
    },
    {
      name: 'yearlyDiscountLabel',
      type: 'text',
      label: 'Yearly Discount Badge Text',
      defaultValue: 'Save 20%',
    },
    {
      name: 'plans',
      type: 'array',
      label: 'Pricing Plans',
      minRows: 1,
      maxRows: 3,
      fields: [
        {
          name: 'label',
          type: 'text',
          label: 'Plan Label (e.g. BASIC)',
          required: true,
        },
        {
          name: 'featured',
          type: 'checkbox',
          label: 'Featured (dark card)',
          defaultValue: false,
        },
        {
          name: 'monthlyPrice',
          type: 'text',
          label: 'Monthly Price (e.g. ₹4,999)',
          required: true,
        },
        {
          name: 'yearlyPrice',
          type: 'text',
          label: 'Yearly Price (e.g. ₹3,999)',
          required: true,
        },
        {
          name: 'priceSuffix',
          type: 'text',
          label: 'Price Suffix',
          defaultValue: '/month · billed monthly',
        },
        {
          name: 'yearlySuffix',
          type: 'text',
          label: 'Yearly Price Suffix',
          defaultValue: '/month · billed yearly',
        },
        {
          name: 'features',
          type: 'array',
          label: 'Features',
          fields: [
            {
              name: 'text',
              type: 'text',
              label: 'Feature Text',
              required: true,
            },
            {
              name: 'included',
              type: 'checkbox',
              label: 'Included',
              defaultValue: true,
            },
          ],
        },
        {
          name: 'buttonLabel',
          type: 'text',
          label: 'Button Label',
          defaultValue: 'Get Started',
        },
        {
          name: 'buttonUrl',
          type: 'text',
          label: 'Button URL',
          defaultValue: '/enroll',
        },
      ],
      defaultValue: [
        {
          label: 'BASIC',
          featured: false,
          monthlyPrice: '₹4,999',
          yearlyPrice: '₹3,999',
          priceSuffix: '/month · billed monthly',
          yearlySuffix: '/month · billed yearly',
          features: [
            { text: '2 group classes/week', included: true },
            { text: 'Digital learning materials', included: true },
            { text: 'Progress tracking', included: true },
            { text: 'Community forum access', included: true },
            { text: 'Private sessions', included: false },
            { text: 'Exam prep', included: false },
          ],
          buttonLabel: 'Get Started',
          buttonUrl: '/enroll',
        },
        {
          label: 'PRO',
          featured: true,
          monthlyPrice: '₹8,999',
          yearlyPrice: '₹7,199',
          priceSuffix: '/month · billed monthly',
          yearlySuffix: '/month · billed yearly',
          features: [
            { text: '4 group classes/week', included: true },
            { text: '2 private sessions/month', included: true },
            { text: 'Premium materials', included: true },
            { text: 'Exam prep included', included: true },
            { text: '1-on-1 advisor support', included: false },
            { text: 'Certificate guarantee', included: false },
          ],
          buttonLabel: 'Get Started',
          buttonUrl: '/enroll',
        },
        {
          label: 'PREMIUM',
          featured: false,
          monthlyPrice: '₹14,999',
          yearlyPrice: '₹11,999',
          priceSuffix: '/month · billed monthly',
          yearlySuffix: '/month · billed yearly',
          features: [
            { text: 'Unlimited group classes', included: true },
            { text: '8 private sessions/month', included: true },
            { text: 'All materials included', included: true },
            { text: 'Priority scheduling', included: true },
            { text: 'Dedicated coach', included: false },
            { text: 'Multiple languages', included: false },
          ],
          buttonLabel: 'Get Started',
          buttonUrl: '/enroll',
        },
      ],
    },
  ],
}
