/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | {
        headingMain: string;
        headingAccent: string;
        subtext?: string | null;
        primaryButton?: {
          label?: string | null;
          url?: string | null;
        };
        secondaryButton?: {
          label?: string | null;
          url?: string | null;
        };
        languageTags?:
          | {
              flag?: string | null;
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        moreLanguagesCount?: number | null;
        satisfactionCard?: {
          label?: string | null;
          value?: string | null;
          subtext?: string | null;
        };
        experienceCard?: {
          label?: string | null;
          value?: string | null;
          badge?: string | null;
        };
        chartTitle?: string | null;
        chartBars?:
          | {
              code?: string | null;
              language?: string | null;
              percentage?: number | null;
              color?: ('sage' | 'brown' | 'yellow' | 'lightGreen') | null;
              id?: string | null;
            }[]
          | null;
        statsRow?:
          | {
              value?: string | null;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroStats';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        statCard?: {
          number?: string | null;
          description?: string | null;
          badges?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        paragraphs?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        primaryButton?: {
          label?: string | null;
          url?: string | null;
        };
        phone?: {
          label?: string | null;
          number?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutIntro';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        subtext?: string | null;
        languages?:
          | {
              code: string;
              name: string;
              level?: string | null;
              tags?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'languagesOffered';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        subtext?: string | null;
        tabs?:
          | {
              tabLabel: string;
              cards?:
                | {
                    title: string;
                    price: string;
                    priceSuffix?: string | null;
                    featured?: boolean | null;
                    details?:
                      | {
                          label?: string | null;
                          value?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                    buttonLabel?: string | null;
                    buttonUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'coursesPrograms';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        steps?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'processSteps';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        subtext?: string | null;
        instructors?:
          | {
              photo?: (string | null) | Media;
              name: string;
              languages?: string | null;
              bio?: string | null;
              profileUrl?: string | null;
              testimonial?: {
                quote?: string | null;
                rating?: number | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faculty';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        testimonials?:
          | {
              quote: string;
              avatar?: (string | null) | Media;
              name: string;
              meta?: string | null;
              rating?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'studentStories';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        yearlyDiscountLabel?: string | null;
        plans?:
          | {
              label: string;
              featured?: boolean | null;
              monthlyPrice: string;
              yearlyPrice: string;
              priceSuffix?: string | null;
              yearlySuffix?: string | null;
              features?:
                | {
                    text: string;
                    included?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              buttonLabel?: string | null;
              buttonUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricing';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        certifications?:
          | {
              icon?: (string | null) | Media;
              emoji?: string | null;
              name: string;
              meta?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'certifications';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        subtext?: string | null;
        questions?:
          | {
              question: string;
              options?:
                | {
                    text: string;
                    score?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        results?:
          | {
              minScore: number;
              maxScore: number;
              emoji?: string | null;
              level: string;
              recommendation?: string | null;
              recommendationUrl?: string | null;
              description?: string | null;
              ctaLabel?: string | null;
              ctaUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'selfAssessment';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        /**
         * Select a form created in the Forms collection.
         */
        form: string | Form;
        locationName?: string | null;
        locationAddress?: string | null;
        mapUrl?: string | null;
        phone?: string | null;
        email?: string | null;
        hours?: string | null;
        socials?:
          | {
              platform: 'facebook' | 'instagram' | 'x' | 'linkedin' | 'youtube';
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        eyebrow?: string | null;
        headingMain: string;
        headingAccent?: string | null;
        subtext?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        image?: (string | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutHero';
      }
    | {
        missionEyebrow?: string | null;
        missionHeading?: string | null;
        missionText?: string | null;
        visionEyebrow?: string | null;
        visionHeading?: string | null;
        visionText?: string | null;
        values?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutMission';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        milestones?:
          | {
              year: string;
              title: string;
              description?: string | null;
              emoji?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutTimeline';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        subtext?: string | null;
        members?:
          | {
              photo?: (string | null) | Media;
              name: string;
              role: string;
              bio?: string | null;
              languages?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutTeam';
      }
    | {
        heading?: string | null;
        subtext?: string | null;
        primaryLabel?: string | null;
        primaryUrl?: string | null;
        secondaryLabel?: string | null;
        secondaryUrl?: string | null;
        badges?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutCta';
      }
    | {
        eyebrow?: string | null;
        headingMain: string;
        headingAccent?: string | null;
        subtext?: string | null;
        searchPlaceholder?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'languagesHero';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        filterLabel?: string | null;
        languages?:
          | {
              flag?: string | null;
              code: string;
              name: string;
              nativeName?: string | null;
              region?: string | null;
              level?: string | null;
              students?: string | null;
              instructors?: number | null;
              tags?:
                | {
                    tag?: string | null;
                    id?: string | null;
                  }[]
                | null;
              featured?: boolean | null;
              url?: string | null;
              color?: ('sage' | 'brown' | 'yellow' | 'black') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'languagesGrid';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        features?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'languageWhy';
      }
    | {
        heading?: string | null;
        subtext?: string | null;
        primaryLabel?: string | null;
        primaryUrl?: string | null;
        secondaryLabel?: string | null;
        secondaryUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'languageCta';
      }
    | {
        eyebrow?: string | null;
        headingMain: string;
        headingAccent?: string | null;
        subtext?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'coursesHero';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        courses?:
          | {
              flag?: string | null;
              language: string;
              title: string;
              format?: ('group' | 'private' | 'intensive' | 'online' | 'business') | null;
              level?: string | null;
              duration?: string | null;
              sessions?: string | null;
              classSize?: string | null;
              price: string;
              pricePeriod?: string | null;
              featured?: boolean | null;
              url?: string | null;
              tags?:
                | {
                    tag?: string | null;
                    id?: string | null;
                  }[]
                | null;
              highlights?:
                | {
                    text?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'coursesList';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        formats?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              bestFor?: string | null;
              price?: string | null;
              featured?: boolean | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'coursesCompare';
      }
    | {
        heading?: string | null;
        subtext?: string | null;
        primaryLabel?: string | null;
        primaryUrl?: string | null;
        secondaryLabel?: string | null;
        secondaryUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'coursesCta';
      }
    | {
        eyebrow?: string | null;
        headingMain: string;
        headingAccent?: string | null;
        subtext?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'facultyHero';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        instructors?:
          | {
              photo?: (string | null) | Media;
              name: string;
              role?: string | null;
              languages?: string | null;
              experience?: string | null;
              nationality?: string | null;
              bio?: string | null;
              profileUrl?: string | null;
              specialisms?:
                | {
                    tag?: string | null;
                    id?: string | null;
                  }[]
                | null;
              certifications?:
                | {
                    cert?: string | null;
                    id?: string | null;
                  }[]
                | null;
              testimonial?: {
                quote?: string | null;
                studentName?: string | null;
                studentMeta?: string | null;
                rating?: number | null;
              };
              featured?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'facultyGrid';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        subtext?: string | null;
        standards?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'facultyPhilosophy';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        subtext?: string | null;
        perks?:
          | {
              icon?: string | null;
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        secondaryLabel?: string | null;
        secondaryUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'facultyJoin';
      }
    | {
        eyebrow?: string | null;
        headingMain: string;
        headingAccent?: string | null;
        subtext?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingHero';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        yearlyDiscountLabel?: string | null;
        plans?:
          | {
              label: string;
              description?: string | null;
              featured?: boolean | null;
              monthlyPrice: string;
              yearlyPrice: string;
              priceSuffix?: string | null;
              yearlySuffix?: string | null;
              features?:
                | {
                    text: string;
                    included?: boolean | null;
                    highlight?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              buttonLabel?: string | null;
              buttonUrl?: string | null;
              badge?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingPlans';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        subtext?: string | null;
        addons?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              price: string;
              pricePeriod?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingAddOns';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        faqs?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingFaq';
      }
    | {
        heading?: string | null;
        subtext?: string | null;
        guarantees?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingGuarantee';
      }
    | {
        heading?: string | null;
        subtext?: string | null;
        primaryLabel?: string | null;
        primaryUrl?: string | null;
        secondaryLabel?: string | null;
        secondaryUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingCta';
      }
    | {
        eyebrow?: string | null;
        headingMain: string;
        headingAccent?: string | null;
        subtext?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactHero';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        subtext?: string | null;
        form: string | Form;
        locationName?: string | null;
        locationAddress?: string | null;
        mapUrl?: string | null;
        contactDetails?:
          | {
              type: 'phone' | 'email' | 'hours' | 'whatsapp';
              label?: string | null;
              value: string;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        socials?:
          | {
              platform: 'facebook' | 'instagram' | 'x' | 'linkedin' | 'youtube';
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactFormSection';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        offices?:
          | {
              emoji?: string | null;
              name: string;
              address: string;
              phone?: string | null;
              email?: string | null;
              hours?: string | null;
              mapUrl?: string | null;
              featured?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactOffices';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        faqs?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactFaq';
      }
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        heroStats?:
          | T
          | {
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              languageTags?:
                | T
                | {
                    flag?: T;
                    name?: T;
                    id?: T;
                  };
              moreLanguagesCount?: T;
              satisfactionCard?:
                | T
                | {
                    label?: T;
                    value?: T;
                    subtext?: T;
                  };
              experienceCard?:
                | T
                | {
                    label?: T;
                    value?: T;
                    badge?: T;
                  };
              chartTitle?: T;
              chartBars?:
                | T
                | {
                    code?: T;
                    language?: T;
                    percentage?: T;
                    color?: T;
                    id?: T;
                  };
              statsRow?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutIntro?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              statCard?:
                | T
                | {
                    number?: T;
                    description?: T;
                    badges?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                  };
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              primaryButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              phone?:
                | T
                | {
                    label?: T;
                    number?: T;
                  };
              id?: T;
              blockName?: T;
            };
        languagesOffered?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              languages?:
                | T
                | {
                    code?: T;
                    name?: T;
                    level?: T;
                    tags?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coursesPrograms?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              tabs?:
                | T
                | {
                    tabLabel?: T;
                    cards?:
                      | T
                      | {
                          title?: T;
                          price?: T;
                          priceSuffix?: T;
                          featured?: T;
                          details?:
                            | T
                            | {
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faculty?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              instructors?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    languages?: T;
                    bio?: T;
                    profileUrl?: T;
                    testimonial?:
                      | T
                      | {
                          quote?: T;
                          rating?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        studentStories?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    avatar?: T;
                    name?: T;
                    meta?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              yearlyDiscountLabel?: T;
              plans?:
                | T
                | {
                    label?: T;
                    featured?: T;
                    monthlyPrice?: T;
                    yearlyPrice?: T;
                    priceSuffix?: T;
                    yearlySuffix?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          included?: T;
                          id?: T;
                        };
                    buttonLabel?: T;
                    buttonUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certifications?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              certifications?:
                | T
                | {
                    icon?: T;
                    emoji?: T;
                    name?: T;
                    meta?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        selfAssessment?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              questions?:
                | T
                | {
                    question?: T;
                    options?:
                      | T
                      | {
                          text?: T;
                          score?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              results?:
                | T
                | {
                    minScore?: T;
                    maxScore?: T;
                    emoji?: T;
                    level?: T;
                    recommendation?: T;
                    recommendationUrl?: T;
                    description?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              form?: T;
              locationName?: T;
              locationAddress?: T;
              mapUrl?: T;
              phone?: T;
              email?: T;
              hours?: T;
              socials?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutHero?:
          | T
          | {
              eyebrow?: T;
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        aboutMission?:
          | T
          | {
              missionEyebrow?: T;
              missionHeading?: T;
              missionText?: T;
              visionEyebrow?: T;
              visionHeading?: T;
              visionText?: T;
              values?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutTimeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              milestones?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    emoji?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutTeam?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              members?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    role?: T;
                    bio?: T;
                    languages?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutCta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              badges?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        languagesHero?:
          | T
          | {
              eyebrow?: T;
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              searchPlaceholder?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        languagesGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              filterLabel?: T;
              languages?:
                | T
                | {
                    flag?: T;
                    code?: T;
                    name?: T;
                    nativeName?: T;
                    region?: T;
                    level?: T;
                    students?: T;
                    instructors?: T;
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    featured?: T;
                    url?: T;
                    color?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        languageWhy?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        languageCta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              id?: T;
              blockName?: T;
            };
        coursesHero?:
          | T
          | {
              eyebrow?: T;
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coursesList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              courses?:
                | T
                | {
                    flag?: T;
                    language?: T;
                    title?: T;
                    format?: T;
                    level?: T;
                    duration?: T;
                    sessions?: T;
                    classSize?: T;
                    price?: T;
                    pricePeriod?: T;
                    featured?: T;
                    url?: T;
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    highlights?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coursesCompare?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              formats?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    bestFor?: T;
                    price?: T;
                    featured?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coursesCta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              id?: T;
              blockName?: T;
            };
        facultyHero?:
          | T
          | {
              eyebrow?: T;
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        facultyGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              instructors?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    role?: T;
                    languages?: T;
                    experience?: T;
                    nationality?: T;
                    bio?: T;
                    profileUrl?: T;
                    specialisms?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    certifications?:
                      | T
                      | {
                          cert?: T;
                          id?: T;
                        };
                    testimonial?:
                      | T
                      | {
                          quote?: T;
                          studentName?: T;
                          studentMeta?: T;
                          rating?: T;
                        };
                    featured?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        facultyPhilosophy?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              standards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        facultyJoin?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              perks?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              id?: T;
              blockName?: T;
            };
        pricingHero?:
          | T
          | {
              eyebrow?: T;
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingPlans?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              yearlyDiscountLabel?: T;
              plans?:
                | T
                | {
                    label?: T;
                    description?: T;
                    featured?: T;
                    monthlyPrice?: T;
                    yearlyPrice?: T;
                    priceSuffix?: T;
                    yearlySuffix?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          included?: T;
                          highlight?: T;
                          id?: T;
                        };
                    buttonLabel?: T;
                    buttonUrl?: T;
                    badge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingAddOns?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              addons?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    price?: T;
                    pricePeriod?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingFaq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingGuarantee?:
          | T
          | {
              heading?: T;
              subtext?: T;
              guarantees?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        pricingCta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              id?: T;
              blockName?: T;
            };
        contactHero?:
          | T
          | {
              eyebrow?: T;
              headingMain?: T;
              headingAccent?: T;
              subtext?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactFormSection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              form?: T;
              locationName?: T;
              locationAddress?: T;
              mapUrl?: T;
              contactDetails?:
                | T
                | {
                    type?: T;
                    label?: T;
                    value?: T;
                    url?: T;
                    id?: T;
                  };
              socials?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactOffices?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              offices?:
                | T
                | {
                    emoji?: T;
                    name?: T;
                    address?: T;
                    phone?: T;
                    email?: T;
                    hours?: T;
                    mapUrl?: T;
                    featured?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactFaq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Upload your site logo. Recommended size: 200x60px.
   */
  logo?: (string | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * The call-to-action button displayed on the right side of the header.
   */
  ctaButton: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Upload your footer logo. Recommended size: 200x60px.
   */
  logo?: (string | null) | Media;
  newsletter?: {
    icon?: (string | null) | Media;
    headingMain?: string | null;
    headingAccent?: string | null;
    subtext?: string | null;
    badgeText?: string | null;
    languageOptions?:
      | {
          language?: string | null;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Add third-party tracking scripts. These are injected directly into your site.
   */
  scripts?: {
    /**
     * Scripts injected inside <head>. Use for Google Tag Manager, Meta Pixel, analytics init scripts, etc.
     */
    headScripts?:
      | {
          label?: string | null;
          position?: ('start' | 'end') | null;
          /**
           * Paste the full <script> tag or inline JS. Supports <script>, <noscript>, and <link> tags.
           */
          script?: string | null;
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Scripts injected immediately after <body> opens. Use for Google Tag Manager noscript fallback, etc.
     */
    bodyStartScripts?:
      | {
          label?: string | null;
          /**
           * Paste the full <script> or <noscript> tag.
           */
          script?: string | null;
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Scripts injected just before </body> closes. Use for chat widgets, lazy-loaded analytics, Intercom, Crisp, etc.
     */
    footerScripts?:
      | {
          label?: string | null;
          /**
           * Paste the full <script> tag. Loads after page content — ideal for non-critical third-party scripts.
           */
          script?: string | null;
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  newsletter?:
    | T
    | {
        icon?: T;
        headingMain?: T;
        headingAccent?: T;
        subtext?: T;
        badgeText?: T;
        languageOptions?:
          | T
          | {
              language?: T;
              id?: T;
            };
        buttonText?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  scripts?:
    | T
    | {
        headScripts?:
          | T
          | {
              label?: T;
              position?: T;
              script?: T;
              enabled?: T;
              id?: T;
            };
        bodyStartScripts?:
          | T
          | {
              label?: T;
              script?: T;
              enabled?: T;
              id?: T;
            };
        footerScripts?:
          | T
          | {
              label?: T;
              script?: T;
              enabled?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}